"use client";
import { GameState } from "./GameBoard";

export const initialGameState: GameState = {
  currentPlayer: {
    id: 1,
    gems: { diamond: 0, sapphire: 0, emerald: 0, ruby: 0, onyx: 0, joker: 0 },
    reservedCards: [],
    purchasedCards: [],
    points: 0,
    nobleCards: [],
  },
  players: [
    {
      id: 2,
      gems: { diamond: 0, sapphire: 0, emerald: 0, ruby: 0, onyx: 0, joker: 0 },
      reservedCards: [],
      purchasedCards: [],
      points: 0,
      nobleCards: [],
    },
    {
      id: 3,
      gems: { diamond: 0, sapphire: 1, emerald: 0, ruby: 0, onyx: 0, joker: 0 },
      reservedCards: [],
      purchasedCards: ["diamond", "diamond"],
      points: 0,
      nobleCards: [],
    },
    {
      id: 4,
      gems: { diamond: 0, sapphire: 0, emerald: 0, ruby: 0, onyx: 0, joker: 0 },
      reservedCards: [],
      purchasedCards: [],
      points: 0,
      nobleCards: [],
    },
  ],
  gemTokens: {
    diamond: 7,
    sapphire: 7,
    emerald: 7,
    ruby: 7,
    onyx: 7,
    joker: 6,
  },
  developmentCards: [
    // Level 1 Cards
    {
      id: 1,
      level: 1,
      cost: { diamond: 1, sapphire: 0, emerald: 0, ruby: 0, onyx: 1, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 2,
      level: 1,
      cost: { diamond: 0, sapphire: 0, emerald: 0, ruby: 1, onyx: 0, joker: 0 },
      points: 0,
      gemType: "sapphire",
    },
    {
      id: 3,
      level: 1,
      cost: { diamond: 0, sapphire: 0, emerald: 0, ruby: 0, onyx: 1, joker: 0 },
      points: 0,
      gemType: "emerald",
    },
    {
      id: 4,
      level: 1,
      cost: { diamond: 0, sapphire: 0, emerald: 1, ruby: 1, onyx: 0, joker: 0 },
      points: 1,
      gemType: "onyx",
    },
    {
      id: 5,
      level: 1,
      cost: { diamond: 0, sapphire: 0, emerald: 0, ruby: 2, onyx: 0, joker: 0 },
      points: 1,
      gemType: "ruby",
    },
    {
      id: 6,
      level: 1,
      cost: { diamond: 1, sapphire: 1, emerald: 0, ruby: 0, onyx: 0, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 7,
      level: 1,
      cost: { diamond: 0, sapphire: 1, emerald: 0, ruby: 1, onyx: 1, joker: 0 },
      points: 0,
      gemType: "ruby",
    },
    {
      id: 8,
      level: 1,
      cost: { diamond: 1, sapphire: 0, emerald: 1, ruby: 0, onyx: 0, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 9,
      level: 1,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 0, onyx: 1, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 10,
      level: 1,
      cost: { diamond: 1, sapphire: 0, emerald: 1, ruby: 0, onyx: 1, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 11,
      level: 1,
      cost: { diamond: 1, sapphire: 0, emerald: 1, ruby: 1, onyx: 0, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 12,
      level: 1,
      cost: { diamond: 1, sapphire: 0, emerald: 0, ruby: 1, onyx: 1, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 13,
      level: 1,
      cost: { diamond: 1, sapphire: 0, emerald: 0, ruby: 1, onyx: 1, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 14,
      level: 1,
      cost: { diamond: 1, sapphire: 0, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 15,
      level: 1,
      cost: { diamond: 2, sapphire: 1, emerald: 0, ruby: 0, onyx: 1, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 16,
      level: 1,
      cost: { diamond: 1, sapphire: 0, emerald: 1, ruby: 0, onyx: 1, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 17,
      level: 1,
      cost: { diamond: 0, sapphire: 1, emerald: 0, ruby: 0, onyx: 1, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 18,
      level: 1,
      cost: { diamond: 1, sapphire: 0, emerald: 0, ruby: 0, onyx: 1, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 19,
      level: 1,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 0, onyx: 0, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    {
      id: 20,
      level: 1,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 1, onyx: 0, joker: 0 },
      points: 0,
      gemType: "diamond",
    },
    // Add more level 1 cards as needed
    // Level 2 Cards
    {
      id: 21,
      level: 2,
      cost: { diamond: 0, sapphire: 0, emerald: 2, ruby: 1, onyx: 0, joker: 0 },
      points: 2,
      gemType: "diamond",
    },
    {
      id: 22,
      level: 2,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 2,
      gemType: "ruby",
    },
    {
      id: 23,
      level: 2,
      cost: { diamond: 0, sapphire: 2, emerald: 2, ruby: 0, onyx: 0, joker: 0 },
      points: 3,
      gemType: "ruby",
    },
    {
      id: 24,
      level: 2,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 2,
      gemType: "ruby",
    },
    {
      id: 25,
      level: 2,
      cost: { diamond: 0, sapphire: 2, emerald: 2, ruby: 0, onyx: 0, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
    {
      id: 26,
      level: 2,
      cost: { diamond: 0, sapphire: 0, emerald: 2, ruby: 1, onyx: 0, joker: 0 },
      points: 2,
      gemType: "diamond",
    },
    {
      id: 27,
      level: 2,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 2,
      gemType: "diamond",
    },
    {
      id: 28,
      level: 2,
      cost: { diamond: 0, sapphire: 2, emerald: 2, ruby: 0, onyx: 0, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
    {
      id: 29,
      level: 2,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 2,
      gemType: "diamond",
    },
    {
      id: 30,
      level: 2,
      cost: { diamond: 0, sapphire: 2, emerald: 2, ruby: 0, onyx: 0, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
    {
      id: 31,
      level: 2,
      cost: { diamond: 0, sapphire: 0, emerald: 2, ruby: 1, onyx: 0, joker: 0 },
      points: 2,
      gemType: "diamond",
    },
    {
      id: 32,
      level: 2,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 2,
      gemType: "diamond",
    },
    {
      id: 33,
      level: 2,
      cost: { diamond: 0, sapphire: 2, emerald: 2, ruby: 0, onyx: 0, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
    {
      id: 34,
      level: 2,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 2,
      gemType: "diamond",
    },
    {
      id: 35,
      level: 2,
      cost: { diamond: 0, sapphire: 2, emerald: 2, ruby: 0, onyx: 0, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
    {
      id: 36,
      level: 2,
      cost: { diamond: 0, sapphire: 0, emerald: 2, ruby: 1, onyx: 0, joker: 0 },
      points: 2,
      gemType: "diamond",
    },
    {
      id: 37,
      level: 2,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 2,
      gemType: "diamond",
    },
    {
      id: 38,
      level: 2,
      cost: { diamond: 0, sapphire: 2, emerald: 2, ruby: 0, onyx: 0, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
    {
      id: 39,
      level: 2,
      cost: { diamond: 0, sapphire: 1, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 2,
      gemType: "diamond",
    },
    {
      id: 40,
      level: 2,
      cost: { diamond: 0, sapphire: 2, emerald: 2, ruby: 0, onyx: 0, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
    // Add more level 2 cards as needed
    // Level 3 Cards
    {
      id: 41,
      level: 3,
      cost: { diamond: 1, sapphire: 2, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 4,
      gemType: "diamond",
    },
    {
      id: 42,
      level: 3,
      cost: { diamond: 0, sapphire: 3, emerald: 0, ruby: 2, onyx: 2, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 43,
      level: 3,
      cost: { diamond: 3, sapphire: 0, emerald: 0, ruby: 3, onyx: 0, joker: 0 },
      points: 5,
      gemType: "ruby",
    },
    {
      id: 44,
      level: 3,
      cost: { diamond: 1, sapphire: 2, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 4,
      gemType: "diamond",
    },
    {
      id: 45,
      level: 3,
      cost: { diamond: 0, sapphire: 3, emerald: 0, ruby: 2, onyx: 2, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 46,
      level: 3,
      cost: { diamond: 3, sapphire: 0, emerald: 0, ruby: 3, onyx: 0, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 47,
      level: 3,
      cost: { diamond: 3, sapphire: 0, emerald: 0, ruby: 3, onyx: 0, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 48,
      level: 3,
      cost: { diamond: 1, sapphire: 2, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 4,
      gemType: "diamond",
    },
    {
      id: 49,
      level: 3,
      cost: { diamond: 0, sapphire: 3, emerald: 0, ruby: 2, onyx: 2, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 50,
      level: 3,
      cost: { diamond: 3, sapphire: 0, emerald: 0, ruby: 3, onyx: 0, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 51,
      level: 3,
      cost: { diamond: 1, sapphire: 2, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 4,
      gemType: "diamond",
    },
    {
      id: 52,
      level: 3,
      cost: { diamond: 0, sapphire: 3, emerald: 0, ruby: 2, onyx: 2, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 53,
      level: 3,
      cost: { diamond: 3, sapphire: 0, emerald: 0, ruby: 3, onyx: 0, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 54,
      level: 3,
      cost: { diamond: 1, sapphire: 2, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 4,
      gemType: "diamond",
    },
    {
      id: 55,
      level: 3,
      cost: { diamond: 0, sapphire: 3, emerald: 0, ruby: 2, onyx: 2, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 56,
      level: 3,
      cost: { diamond: 3, sapphire: 0, emerald: 0, ruby: 3, onyx: 0, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 57,
      level: 3,
      cost: { diamond: 3, sapphire: 0, emerald: 0, ruby: 3, onyx: 0, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 58,
      level: 3,
      cost: { diamond: 1, sapphire: 2, emerald: 1, ruby: 1, onyx: 1, joker: 0 },
      points: 4,
      gemType: "diamond",
    },
    {
      id: 59,
      level: 3,
      cost: { diamond: 0, sapphire: 3, emerald: 0, ruby: 2, onyx: 2, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 60,
      level: 3,
      cost: { diamond: 3, sapphire: 0, emerald: 0, ruby: 3, onyx: 0, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    // Add more level 3 cards as needed
  ],
  nobleTiles: [
    {
      id: 1,
      level: 0,
      cost: { diamond: 0, sapphire: 4, emerald: 0, ruby: 4, onyx: 3, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
    {
      id: 2,
      level: 0,
      cost: { diamond: 3, sapphire: 0, emerald: 0, ruby: 3, onyx: 0, joker: 0 },
      points: 5,
      gemType: "diamond",
    },
    {
      id: 3,
      level: 0,
      cost: { diamond: 3, sapphire: 0, emerald: 0, ruby: 3, onyx: 0, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
    {
      id: 4,
      level: 0,
      cost: { diamond: 0, sapphire: 4, emerald: 4, ruby: 3, onyx: 0, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
    {
      id: 5,
      level: 0,
      cost: { diamond: 0, sapphire: 0, emerald: 2, ruby: 3, onyx: 2, joker: 0 },
      points: 3,
      gemType: "diamond",
    },
  ],
  selectedGem: [],
};
